### ISSUE TITLE
TypeScript suggestions for $dayjs not working in dayjs-nuxt 2.1.11 templates

### ISSUE THREAD

**Issue by lanseria** [fumeapp/dayjs#54]
**Title:** TypeScript suggestions for `$dayjs` not working in dayjs-nuxt 2.1.11 templates

**Description:**
After upgrading to the latest dayjs-nuxt 2.1.11, TypeScript no longer provides suggestions for the `$dayjs` object in template files. It seems that the `$dayjs` property is not recognized in the component's type definition.

**Error message:**
```
Property '$dayjs' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, {}>, { initPumpCurrentValues: typeof initPumpCurrentValues; 参数类型Map: typeof 参数类型Map; 参数单位Map: typeof 参数单位Map; 参数位置Map: typeof 参数位置Map; ... 9 more ...; handleEdit: typeof handleEdit; }, ... 23 more ..., {}>'. ts-plugin(2339)
```

![image](https://github.com/user-attachments/assets/73877d02-09f5-4031-9948-bd6e401d4920)
