### ISSUE TITLE
Error 500 when plugin extend

### ISSUE THREAD

**Issue by Jorgagu** [fumeapp/dayjs#19]
Hello, we have an issue when starting the Nuxt server build.

Here is how to reproduce: [https://stackblitz.com/edit/nuxt-starter-h7nv5v](https://stackblitz.com/edit/nuxt-starter-h7nv5v)

You'll need to run these commands in the StackBlitz terminal.

Stop the dev script using:
```bash
CTRL + C
```

Build the server:
```bash
yarn build
```

Then launch it with:
```bash
node .output/server/index.mjs
```

You should encounter a 500 error with the message "E is not a function".
It appears to be related to the plugin's extend function causing this error.

**Comment by acidjazz** [comment]
definitely duplicateable in stackblitz, node crashed a couples times as well, ill try and duplicate this locally

**Comment by GaborTorma** [comment]
dayjs.extend is not a function: 
![Snag_188913fe](https://github.com/fumeapp/dayjs/assets/11255009/b152796a-79bb-48eb-955e-1c9426bc8595)


You can reproduce here: https://stackblitz.com/edit/nuxt-starter-7hgmnz?file=plugins%2Fdayjs.ts
Locally has the same error message.

**Comment by Jorgagu** [comment]
Thanks for your answers @GaborTorma and @acidjazz 

This error is a new error due to version v2 because before that there was no Dayjs Type and it was all in any.

But this function should exist because we need it to extend a plugin as it says here https://github.com/fumeapp/dayjs#more-extending.

**Comment by GaborTorma** [comment]
Same issue with `dayjs.locale` function.

**Comment by compilekaiten** [comment]
Was trying to use Duration, but adding it to `nuxt.config.ts` doesn't expose it.

Tried making a plugin, and I encounter the same issue.

**Comment by GaborTorma** [comment]
Still not working in 2.0.5 version. I updated the repo: https://stackblitz.com/edit/nuxt-starter-7hgmnz?file=package.json,plugins%2Fdayjs.ts

The problem is useDayjs returns the instance of DayJS class not the namespace.

**Comment by acidjazz** [comment]
v2.1.1 now supports external plugins through configuration

I reverted the composable back to just returning dayjs to help accomodate

https://github.com/fumeapp/dayjs#more-extending

**Comment by GaborTorma** [comment]
I made a [pr](https://github.com/fumeapp/dayjs/pull/28) for this issue.
